services:
    nginx:
        image: nginx:alpine
        container_name: nginx
        volumes:
            - "./docker/nginx/local.conf:/etc/nginx/conf.d/default.conf"
            - "./:/var/www/html"
            - "./docker/data/nginx/log:/var/log/nginx"
        ports:
            - 80:80
            - 8000:8000
        restart: unless-stopped
        depends_on:
            - php8.2
            - mysqldb
    php8.2:
        image: bitnami/php-fpm:8.2.19
        platform: linux/x86_64
        container_name: php8.2
        restart: unless-stopped
        volumes:
            - "./docker/php/8.2/custom.ini:/opt/bitnami/php/etc/conf.d/custom.ini"
            - "./:/var/www/html"
    myadmin:
        image: phpmyadmin/phpmyadmin
        platform: linux/x86_64
        container_name: phpmyadmin
        ports:
            - 8080:80
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
            - UPLOAD_LIMIT=200M
        restart: unless-stopped
        depends_on:
            - mysqldb
    mysqldb:
        image: mysql:9.1
        platform: linux/x86_64
        container_name: mysql
        restart: unless-stopped
        environment:
            - MYSQL_DATABASE=test
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=test
            - MYSQL_PASSWORD=test
        ports:
            - 3306:3306
        volumes:
            - "./docker/data/db/mysql:/var/lib/mysql"
    chrome:
        image: selenium/node-chrome:4.8.3
        platform: linux/x86_64
        shm_size: 2gb
        depends_on:
            - selenium-hub
        environment:
            - SE_NODE_SESSION_TIMEOUT=2
            - SE_EVENT_BUS_HOST=selenium-hub
            - SE_EVENT_BUS_PUBLISH_PORT=4442
            - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    selenium-hub:
        image: selenium/hub:4.8.3
        platform: linux/x86_64
        container_name: selenium-hub
        ports:
            - 4442-4444:4442-4444

